apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb-cluster-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mb-cluster-1
  template:
    metadata:
      labels:
        app: mb-cluster-1
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/nodal-vigil-434510-h6/mb-repo/mb-app:0.3
        imagePullPolicy: IfNotPresent
        name: mb-app